config/routes.rb
Rails.application.routes.draw do

  root'pages#home'
  
  get 'pages/why'

  get 'pages/home'

  get 'pages/services'

  get 'pages/us'

  get 'pages/contact'

  get 'pages/products'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def why
  end

  def products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">

   <h1 class="footerh">Líderes en soluciones de altura.</h1>
   <div style="margin-left:5%;" class="footerpd">
     <p class="footerp">José Santos Chocano #3116</p>
     <p class="footerp">Colonia Francisco I Madero C.P. 64560</p>
     <p class="footerp">Monterrey, Nuevo León, México</p>
   </div>
   <div class="footerpd">
     <p class="footerp">teléfono:<span class="red">(81) 18-77-61-32 </span></p>
     <p class="footerp">celular:<span class="red">(044) 818-259-06-72</span></p>
     <p class="footerp">email:<span class="red">jbortegon@spidersolutions.com.mx</span></p>
     <p class="developer"> 2017 Spider Solutions de México | maps creation</p>
   </div>
   

</div>

app/views/layouts/_form.html.erb
<form action="https://formspree.io/solucionesdealtura@gmail.com"
      method="POST">

    <textarea id="subject" name="subject" placeholder="Describenos tu asunto" class="textarea"></textarea>

    <input type="text" id="correo" name="correo" placeholder="Correo Electrónico">

    <input type="text" id="nombre" name="nombre" placeholder="Nombre">

    <input type="text" id="interes" name="interes" placeholder="Interés">

    <input type="text" id="celular" name="celular" placeholder="Celular">

    <input type="submit" value="enviar">

  </form>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" id="navx">
  <div class="container-fluid" id="containerfluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= pages_home_path %>">
        <img alt="Brand" id="logo" src="/assets/logospider.jpg">
      </a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= pages_services_path %>" >Servicios y Productos</a></li>
        <li><a href="<%= pages_why_path %>" >¿Porque Spider?</a></li>
        <li><a href="<%= pages_us_path %>" >Acerca de nosotros</a></li>
        <li><a href="<%= pages_contact_path %>">Contacto</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<script>
$( document ).ready(function() {

  });
</script>

app/views/layouts/application.html.erb
!<DOCTYPE html>
<html style="height:100%; margin:0; padding:0; border:0;">
      <head>

         <title>Soluciones de Altura Spider</title>
              <meta charset="utf-8">
              <meta name="description" content="Trabajos en altura">
              <meta name="keywords" content="Trabajos, altura, soluciones, sistemas, limpiafachadas">
              <meta name="author" content=“Alan Munoz">
              <meta property="og:title" content="Spider Solutions" />
              <meta property="og:type" content="website" />
              <meta property="og:url" content="http://spidersolutions.mx"/>
              <meta property="og:image" content="http://ia.media-imdb.com/
              images/rock.jpg" />
              <meta http-equiv="X-UA-Compatible" content="IE=edge">
              <meta name="viewport" content="width=device-width, initial-scale=1">
    
              <link href="https://fonts.googleapis.com/css?family=Inconsolata|Playfair+Display|Vidaloka" rel="stylesheet">
              <link href="https://fonts.googleapis.com/css?family=Ruda" rel="stylesheet">


              <%= csrf_meta_tags %>

              <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
              <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      </head>

  <body style="height:100%; margin:0; padding:0; border:0;";>
    <%= yield %>
  </body>

  <!-- jQuery -->
   <script src="//code.jquery.com/jquery-2.2.1.min.js"></script>
   <script>window.jQuery || document.write('<script src="js/vendor/jquery-2.2.1.min.js"><\/script>')</script>
   <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <!-- scripts concatenated and minified -->
   <script src="js/plugins.js"></script>
   <script src="js/main.js"></script>
  <!-- end concatenated and minified scripts-->
  
</html>

app/views/pages/contact.html.erb
<%= render "layouts/navbar" %>
<span class="margin-container">
</span>

<span class="medbandanawhite">
 <h1 class="contacth" >Contáctanos</h1>
 <p class="contactp">Siempre estamos dispuestos a buscar la <span class="italic"> mejor solución</span> para ti, mándanos tus datos para contactarte lo antes posible.</p>
</span>

<span class="form" >
  <%= render "layouts/form" %>
</span>

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14382.063128059337!2d-100.2826092!3d25.6873415!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd753d83d7513135f!2sSoluciones+de+Altura+E+Ingenier%C3%ADa+S.A.+de+C.V.!5e0!3m2!1sen!2smx!4v1498322376513" width="600" height="450" frameborder="0" class="maps" allowfullscreen></iframe>


<%= render "layouts/footer" %>

app/views/pages/home.html.erb
<%= render "layouts/navbar" %>

<span class="margin-container">
</span>

<span class="background-container">
  <h1 id ="land1" >Líderes en soluciones integrales de altura.</h1>
</span>

<div class="bandana">
        <span class="box3" style="margin-left:.16%;">
          
          <img src="https://ci6.googleusercontent.com/proxy/fyiNd9lwRuB8P7R9y2wPGgbbo049G0S7AA9kv1XLDUn9jgo7z9z-HgrZxzH_ffI_4OcrT95-1B--z1iKIrJ3ByZqtllBJVnyU3w8W9q1KeiX6wrN2kvembxATL-y76AR52lF09hkHV8syId3xw=s0-d-e1-ft#http://rb-ingenieros.com/wp-content/uploads/Trabajos-verticales-sin-andamios-madrid.jpg" class="imgshome">
          <div class="thumbholder">
            <p class="imgthumbcon">CONSTRUCCIÓN</p>
          </div>
          <div class="imgdescphome">
          <p class="imgdescp">Contamos con servicios durante y post-construcción que garantizan el perfecto estado de su edificio para evitar los desembolsos imprevistos, además de evitar el uso de grúas, balsas etc.</p>
          </div>
       </span>

       </span>
        <span class="box3" style="margin-left:.33%;">
          <img src="http://eleforma.es/image/catalog/web/curso-trabajos-en-altura.jpg" class="imgshome">
          <div class="thumbholder">
            <p class="imgthumbind">INDUSTRIA</p>
          </div>
          <div class="imgdescphome">
          <p class="imgdescp">Ofrecemos una variedad de productos industriales, así como trabajos en zonas peligrosas o de difícil acceso, los sistemas empleados garantizan velocidad, eficacia y seguridad.</p>
          </div>
          
        </span>

        </span>
        <span class="box3" style="margin-left:.33%; margin-right:.16%">
          <img src="https://diarioti.com/wp-content/uploads/2016/07/shutterstock_167269976_f11photo_antenas-moviles.jpg" class="imgshome">
          <div class="thumbholder">
          <p class="imgthumbtel">TELECOMUNICACIONES</p>
          </div>
          <div class="imgdescphome">
          <p class="imgdescp">Proveemos soluciones de altura para distintos sectores, adaptándonos a los requerimientos del cliente, incluyendo instalación, mantenimiento etc.</p>
          </div>
          
        </span>
</div> 

<div class="medbandana">
  <h1 class="medbhead">¿Que nos diferencia?</h1>
  <span class="medbbod">
     <p class="medbp">Contamos con personal capacitado y certificado que opera con equipo de seguridad especializado para asegurar el bienestar de nuestros trabajadores y clientes.
     Garantizamos la satisfacción de nuestros clientes a través de proyectos especialmente diseñados para necesidades particulares, ofreciendo soluciones integrales practicas.
     Ofrecemos soluciones teniendo en cuenta al cliente, al evitar usar balsas, logramos ofrecer un trabajo más económico sin interrumpir las operaciones de nuestros clientes.</p>
  </span>
</div>

<%= render "layouts/footer" %>

app/views/pages/services.html.erb
<%= render "layouts/navbar" %>\

<span class="margin-container">
</span>

<div class="serbut">
     <p class="sph">Servicios</p>
</div>

<div class="probut">
     <p class="sph">Productos</p>
</div>

<div class="servsdn">

    <article class="servHeader">
     <p class="servh">Servicios</p>
     <p class="servh2" style="margin-right:1%;" >Telecomunicaciones</p>
     <p class="servh2" >Construcción</p>
     <p class="servh2" >Obras Públicas</p>
     <p class="servh2" >Lineas de Vida</p>
     <p class="servh2" >Consultoría</p>
     <p class="servh2" >Industria</p>
     <p class="servh2" >Taludes</p>
    </article>

    <article class="listArea">
      <ul class="listse">
        <li>Consultoria y auditoria durante construcción para la reducción de vicios ocultos</li>
      <li>Limpieza de fachadas y final de obra</li>
      <li>Inspección de fachadas,diagnostico y reporte de fallas</li>
      <li>Construcción e instalación de fachadas de panel de aluminio y fachadas ventiladas</li>
      <li>Sello y reparación de filtraciones de altura</li>
      <li>Trabajos en espacios confinados</li>
      <li>Sanamientos preventivos</li>
      <li>Pintura de altura</li>  
      <li>Soldadura de altura</li>
      <li>Reparación de estructuras</li>
      <li>Trabajos en zonas de dificil acceso</li>
      <li>Estabilización de taludes</li>
      <li>Montaje de publicidad</li>
      <li>Capacitación y formación para trabajos verticales</li>
      <li>Instalaciones electricas, iluminación, cableado etc.</li>
      <li>Instalacion de lineas de vida</li>
      <li>Impermeabilización y sellado</li>
      <li>Instalación de antenas de telecomunicaciones</li>
      <li>Mantenimiento y revisión de antenas</li>
      <li>Reparación de dificil acceso en antenas</li>
      <li>Ariostramientos</li>
      <li>Rescate en lugares de difícil acceso</li>
      <li>Instalación de placas solares</li>
      <li>Pintura de altura</li>  
      <li>Trabajos de corte en altura</li>
      <li>Refuerzos estructurales</li>
      <li>Enfoscados</li>
     </ul>

    </article>

    <aside class="buttonArea">
    <img src="http://metropolita.es/wp-content/uploads/2015/07/Trabajos-Verticales-Metropolita.png" class="bi2" > 
    
    <img src="http://enerpalformacion.com/wp-content/uploads/2014/09/cursos_trabajos_verticales-940x460.jpg" class="bi3">

    <div class="proret"><p>Ir a productos</p> </div>


    </aside>


</div>

<div class="servpdn">
   <article class="proHeader">
     <span class="servhp">Productos</span>
     <p class="servh2p" >Sistemas Limpiafachadas</p>
     <p class="servh2p">Lineas de vida</p>
     <p class="servh2p">Estructuras</p>
   </article>

   

   <aside class="proImg">

      <p class="prop" >En Spider Solutions contamos con nuestro taller de manufactura y fabricación, esto nos permite ofrecer no solo servicios, sino productos fabricados para las necesidad particulares de cada cliente, somos la unica empresa en México que ofrece Sistemas Limpiafachadas™, estos sistemas facilitan y agilizan la limpieza, revisión y correció de cualquier tipo de fachada.</p>

     <p class="propo">Nuestro equipo de ingenieros y diseñadores de planta trabajaran mano a mano con usted en la construcción de su edificio para diseñar, fabricar e instalar un Sistemas Limpiafachadas™ a su medida, la instalación del sistema no implica el uso de andamios, por lo cual sigue siendo una opción económica con su capital y con su tiempo. </p>

     <p class="propo" style="margin-top:1%;">En nuestro taller también diseñamos y construimos estructuras de acero para distintos usos (fachadas, piezas, aditamentos, lineas de vida etc), los propositos de estas estructuras varian para cada cliente, al igual que los Sistemas Limpiafachadas™, el servicio de elaboración de estructuras incluye el diseño, fabricación e instalación de estos, ya sea en lugar de dificiles accesos o donde el cliente lo requiera.</p>

     <p class="propo">En Spider Solutions desarrollamos constantemente nuevos productos y creemos que cada cliente requiere soluciones particulares y a la medida, <a class="pp"  href="<%= pages_contact_path %>"> contactanos</a> para discutir tu idea o necesidad!</p>


   </aside>

     <article class="proText"> 

     <img  class="imgprop2" src="https://www.amedirh.com.mx/blogrh/wp-content/themes/yootheme/cache/192-294a58f2.jpeg">
     <div class="serret"><p>Ir a servicios</p></div>

   </article>
</div>

 

<script>
  $( document ).ready(function() {
      $('.serbut').click(function(){
        $('.probut').fadeOut();
        $('.serbut').hide();
        $('.sph').hide();
        $('.servsdn').show();
        $('.servh').show();
        $('.servh2').fadeIn();
        $('.listse').fadeIn();
        $('.listsse').fadeIn();
        $('.imgser').fadeIn();
        $('.proret').fadeIn();
         });

    $('.probut').click(function(){
        $('.serbut').hide();
        $('.probut').hide();
        $('.sph').hide();
        $('.servpdn').show();
        $('.servhp').show();
        $('.servh2p').fadeIn();
        $('.prop').fadeIn();
        $('.propo').fadeIn();
        $('.imgprop2').fadeIn();
        $('.serret').fadeIn();
    });

    $('.proret').click(function(){
        $('.servsdn').hide();
        $('.servh').hide();
        $('.servh2').hide();
        $('.listse').hide();
        $('.listsse').hide();
        $('.imgser').hide();
        $('.proret').hide();

        $('.servpdn').show();
        $('.servhp').show();
        $('.servh2p').fadeIn();
        $('.prop').fadeIn();
        $('.propo').fadeIn();
        $('.imgprop2').fadeIn();
        $('.serret').fadeIn();
    });
    $('.serret').click(function(){
        $('.servsdn').show();
        $('.servh').show();
        $('.servh2').fadeIn();
        $('.listse').fadeIn();
        $('.listsse').fadeIn();
        $('.imgser').fadeIn();
        $('.proret').fadeIn();

        $('.servpdn').hide();
        $('.servhp').hide();
        $('.servh2p').hide();
        $('.prop').hide();
        $('.propo').hide();
        $('.imgprop2').hide();
        $('.serret').hide();
         });

});
</script>

<%= render "layouts/footer" %>

app/views/pages/why.html.erb
<%= render "layouts/navbar" %>

<span class="margin-container">
</span>

<span class="whybandana">
  

<div class="whybtton" id="seg_button"> <span>Seguridad </span> </div>
<div class="whybtton" id="cal_button" ><span>Calidad</span> </div>
<div class="whybtton" id="ec_button" ><span>Economía</span> </div>

  <div class="whycontainer">

    <div class="whyimg"> 
      <img class="imgseg" src="http://www.servylimp.es/img/w854_h498_c0-0-854-498/trabajos-en-altura.jpg" style="width:100%;height:100%;"/>
      <img class="imgcal" src="https://cdn.shutterstock.com/shutterstock/videos/3478175/thumb/1.jpg" style="width:100%;height:100%;display:none"/>
      <img class="imgec" src="http://www.cursosaempresas.es/wp-content/uploads/2015/02/altura.jpg" style="width:100%;height:100%;display:none"/>
    </div>
    <div class="whypd"> 
       <p id="whyps" class="whyp"><span class="redbone">Seguridad.</span> Somos una empresa consciente de los riesgos existentes en este rubro, por lo cual todas las adecuaciones de seguridad y anclajes específicos de cada proceso son diseñados e implementados por un especialista certificado que garantiza la seguridad y eficiencia de los trabajos.

       Todos nuestros elementos cuentan con capacitación en técnicas verticales para desempeñar su labor solucionando cualquier eventualidad y utilizando equipo de seguridad especializado para trabajos en altura que reducen la probabilidad de accidentes.</p>

       <p id="whypc" class="whyp"><span class="redbone">Calidad.</span> Además de ofrecer máxima seguridad, garantizamos la calidad de nuestros trabajos, las técnicas que empleamos denominadas como Rope Access permiten el recorte sustancial del tiempo en el cual realizamos nuestros trabajos ya que esto evita la instalación de sistemas más tardados como grúas, andamios, hamacas etc. esto permite realizar el trabajo de una manera más versátil ya que podemos accesar a lugares reducidos, en Spider Solutions nuestros especialidad son las alturas y nuestro fuerte es ser profesionales.</p>

       <p id="whype" class="whyp"><span class="redbone">Economía.</span> Sabemos que su edificio es un activo muy importante, y como cualquier obra requiere constante revisión, el mantenimiento preventivo y correctivo, así como la revisión periódica garantiza la prevención de imprevistos como gastos o daños en su edificación, siendo la opción más económica a largo plazo.

       Contamos con pólizas de mantenimiento que adaptaremos a sus necesidades especificas, de esta manera usted cuenta con un soporte de mantenimiento especializado durante todo el año evitando los grandes desembolsos.</p>
    </div>

   </div>
  
</span>

<script>
  $( document ).ready(function() {
      $('#seg_button').click(function(){
        $('.imgec').hide();
        $('.imgcal').hide();
        $('.imgseg').fadeIn();
        $('#whype').hide();
        $('#whypc').hide();
        $('#whyps').fadeIn();
        });
      $('#cal_button').click(function(){
        $('.imgseg').hide();
        $('.imgec').hide();
        $('.imgcal').fadeIn();
        $('#whype').hide();
        $('#whyps').hide();
        $('#whypc').fadeIn();
        });
      $('#ec_button').click(function(){
        $('.imgseg').hide();
        $('.imgcal').hide();
        $('.imgec').fadeIn();
        $('#whyps').hide();
        $('#whypc').hide();
        $('#whype').fadeIn();
        });
    });
</script>

<%= render "layouts/footer" %>